export const SKILL_ALIASES: Record<string, string[]> = {
  "Node.js": ["node", "nodejs", "node.js"],
  "Express.js": ["express", "expressjs", "express.js"],
  "React.js": ["react", "reactjs", "react.js"],
  "Next.js": ["next", "nextjs", "next.js"],
  "PostgreSQL": ["postgres", "postgresql"],
  "MongoDB": ["mongodb", "mongo"],
  "JavaScript": ["javascript", "js"],
  "TypeScript": ["typescript", "ts"],
  "REST API": ["rest", "rest api", "restful api", "restful apis"],
  "Docker": ["docker"],
  "Kubernetes": ["kubernetes", "k8s"],
  "SQL": ["sql"],
  "Java": ["java"],
  "Python": ["python"],
  "Spring Boot": ["spring boot"],
  "Angular": ["angular", "angularjs"],
  "Kafka": ["kafka"],
  "AWS": ["aws", "amazon web services"],
  "Azure": ["azure"],
  "HTML": ["html", "html5"],
  "CSS": ["css", "css3"],
  "C++": ["c++"],
  "C#": ["c#", "c sharp"],
  ".NET": [".net", "dotnet"],
  "Microservices": ["microservices", "microservice"],
  "Prisma": ["prisma"],
  "Tailwind CSS": ["tailwind", "tailwindcss", "tailwind css"],
  
  // Additional programming languages
  "Go": ["go", "golang"],
  "Rust": ["rust"],
  "Swift": ["swift"],
  "Kotlin": ["kotlin"],
  "Scala": ["scala"],
  "Ruby": ["ruby", "ruby on rails", "rails"],
  "PHP": ["php"],
  "Perl": ["perl"],
  "R": ["r", "r programming"],
  "MATLAB": ["matlab"],
  "Lua": ["lua"],
  "Bash": ["bash", "shell", "shell scripting"],
  "PowerShell": ["powershell"],
  
  // Frontend frameworks
  "Vue.js": ["vue", "vuejs", "vue.js"],
  "Svelte": ["svelte"],
  "Ember.js": ["ember", "emberjs"],
  "Backbone.js": ["backbone", "backbone.js"],
  "jQuery": ["jquery"],
  "Bootstrap": ["bootstrap"],
  "Material-UI": ["material ui", "mui"],
  "Ant Design": ["ant design", "antd"],
  "Chakra UI": ["chakra ui"],
  "Styled Components": ["styled components"],
  "Sass": ["sass", "scss"],
  "Less": ["less"],
  "Stylus": ["stylus"],
  
  // Backend frameworks
  "Django": ["django"],
  "Flask": ["flask"],
  "FastAPI": ["fastapi"],
  "Laravel": ["laravel"],
  "Symfony": ["symfony"],
  "Rails": ["rails", "ruby on rails"],
  "Spring": ["spring", "spring framework"],
  "Hibernate": ["hibernate"],
  "JPA": ["jpa"],
  "MyBatis": ["mybatis"],
  
  // Databases
  "MySQL": ["mysql"],
  "Oracle": ["oracle", "oracle database"],
  "SQL Server": ["sql server", "mssql"],
  "SQLite": ["sqlite"],
  "Redis": ["redis"],
  "Elasticsearch": ["elasticsearch", "elastic"],
  "Cassandra": ["cassandra"],
  "Couchbase": ["couchbase"],
  "Neo4j": ["neo4j"],
  "DynamoDB": ["dynamodb"],
  "Firestore": ["firestore"],
  "Supabase": ["supabase"],
  
  // Cloud & DevOps
  "Google Cloud": ["gcp", "google cloud platform"],
  "Azure DevOps": ["azure devops"],
  "Jenkins": ["jenkins"],
  "GitLab CI": ["gitlab ci"],
  "GitHub Actions": ["github actions"],
  "Terraform": ["terraform"],
  "Ansible": ["ansible"],
  "Puppet": ["puppet"],
  "Chef": ["chef"],
  "Nginx": ["nginx"],
  "Apache": ["apache"],
  "Vagrant": ["vagrant"],
  
  // Testing
  "Jest": ["jest"],
  "Mocha": ["mocha"],
  "Chai": ["chai"],
  "Selenium": ["selenium"],
  "Cypress": ["cypress"],
  "Playwright": ["playwright"],
  "JUnit": ["junit"],
  "TestNG": ["testng"],
  "PyTest": ["pytest"],
  "RSpec": ["rspec"],
  
  // Tools & Technologies
  "Git": ["git", "github", "gitlab", "bitbucket"],
  "Webpack": ["webpack"],
  "Vite": ["vite"],
  "Parcel": ["parcel"],
  "Rollup": ["rollup"],
  "Babel": ["babel"],
  "ESLint": ["eslint"],
  "Prettier": ["prettier"],
  "JIRA": ["jira"],
  "Confluence": ["confluence"],
  "Slack": ["slack"],
  "Figma": ["figma"],
  "Sketch": ["sketch"],
  "Adobe XD": ["adobe xd"],
  
  // Data Science & ML
  "TensorFlow": ["tensorflow", "tf"],
  "PyTorch": ["pytorch"],
  "Keras": ["keras"],
  "Scikit-learn": ["scikit learn", "sklearn"],
  "Pandas": ["pandas"],
  "NumPy": ["numpy"],
  "Jupyter": ["jupyter", "jupyter notebook"],
  "Tableau": ["tableau"],
  "Power BI": ["power bi", "powerbi"],
  
  // Business & Other
  "Agile": ["agile", "scrum", "kanban"],
  "Project Management": ["project management", "pm"],
  "Data Analysis": ["data analysis", "analytics"],
  "Machine Learning": ["machine learning", "ml"],
  "Artificial Intelligence": ["artificial intelligence", "ai"],
  "Deep Learning": ["deep learning", "dl"],
  "Natural Language Processing": ["nlp", "natural language processing"],
  "Computer Vision": ["computer vision", "cv"],
  "Blockchain": ["blockchain", "web3", "ethereum", "bitcoin"],
  "Internet of Things": ["iot", "internet of things"],
  "Cybersecurity": ["cybersecurity", "security", "information security"],
  "DevOps": ["devops", "site reliability engineering", "sre"],
  "CI/CD": ["ci/cd", "continuous integration", "continuous deployment"],
  "API Design": ["api design", "api development"],
  "System Design": ["system design", "architecture"],
  "Performance Optimization": ["performance optimization", "optimization"],
  "Code Review": ["code review", "peer review"],
  "Technical Writing": ["technical writing", "documentation"],
  "Team Leadership": ["team leadership", "leadership", "mentoring"],
  "Problem Solving": ["problem solving", "analytical thinking"],
  "Communication": ["communication", "interpersonal skills"],
  
  // Hardware & Embedded Systems
  "Arduino": ["arduino", "arduino uno", "arduino ide"],
  "ESP32": ["esp32"],
  "Raspberry Pi": ["raspberry pi", "rpi"],
  "Verilog": ["verilog", "systemverilog"],
  "VHDL": ["vhdl"],
  "Microcontrollers": ["microcontroller", "microcontrollers", "mcu"],
  "Embedded Systems": ["embedded systems", "embedded c", "embedded software"],
  "PCB Design": ["pcb design", "pcb layout"],
  "KiCad": ["kicad"],
  "LTSpice": ["ltspice"],
  "PSpice": ["pspice"],
  "Vivado": ["vivado", "xilinx vivado"],
  "Virtuoso": ["virtuoso", "cadence virtuoso"],
  "TCAD": ["tcad", "synopsys tcad"],
  "SolidWorks": ["solidworks"],
  "ANSYS": ["ansys", "ansys cfd"],
  "Simulink": ["simulink"],
  "CST Studio": ["cst studio", "cst"],
  "Mentor Graphics": ["mentor graphics"],
  "FPGA": ["fpga", "field programmable gate array"],
  "Digital Electronics": ["digital electronics", "digital systems"],
  "Analog Electronics": ["analog electronics", "analog circuits"],
  "Signal Processing": ["signal processing", "dsp"],
  "Control Systems": ["control systems", "control logic"],
  "Robotics": ["robotics", "autonomous systems"],
  "Aerodynamics": ["aerodynamics", "cfd analysis"],
  "Ethical Hacking": ["ethical hacking"],
  "Cybersecurity Technician": ["certified cybersecurity technician", "cct"],

  // Modern Web & Tools
  "React Flow": ["react flow", "reactflow"],
  "Framer Motion": ["framer motion", "framer-motion"],
  "Zustand": ["zustand"],
  "Zod": ["zod", "zod validation"],
  "JWT": ["jwt", "jwt authentication"],
  "FFmpeg": ["ffmpeg"],
  "OpenCV": ["opencv"],
  "Trigger.dev": ["trigger.dev", "trigger dev"],
  "Postman": ["postman"],
  "Clerk": ["clerk", "clerk authentication"],
  "Cloudinary": ["cloudinary"],
  "Razorpay": ["razorpay"],
  "OpenAI": ["openai", "openai api", "chatgpt api"],
  "Google Gemini": ["google gemini", "gemini api", "google gemini api"],
  
  // Scientific & HPC
  "Computational Electromagnetics": ["computational electromagnetics", "cem"],
  "Physics": ["physics"],
  "Electrical Engineering": ["electrical engineering", "ee"],
  "Applied Mathematics": ["applied mathematics", "math"],
  "High Performance Computing": ["high performance computing", "hpc"],
  "MPI": ["mpi"],
  "OpenMP": ["openmp"],
  "Fortran": ["fortran"],
  "Linear Algebra": ["linear algebra"],
  "Numerical Methods": ["numerical methods", "numerical algorithms"],
  "Electromagnetic Wave Theory": ["electromagnetic wave theory"],
  "C": ["c"]
};
